version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gobank
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    ports:
      - "5435:5432"
